### PR TITLE
Fix null bug in #329

### PR DESCRIPTION
**Pull request by 18PatZ**
This should fix the appearance of the null entry in the completed-Quests section in the data files, assuming that the issue is caused by duplicate entries in the completedQuests list (when you complete a quest you've completed before). This issue is referenced in pull request #534.

My Spigot name is ShowbizLocket61.

### CODE REVIEW

**Comment by FlyingPikachu** [comment]
@18PatZ Thanks for taking a look! Will try this out shortly. If no 'null' value is made and everything works OK, I'll consider this fix satisfactory per terms.

**Comment by FlyingPikachu** [comment]
@18PatZ So, the 'null' value is gone, but has [been replaced with a duplicate of the quest name](http://imgur.com/a/TXmru).

**Comment by 18PatZ** [comment]
@FlyingPikachu patched.

**Comment by FlyingPikachu** [comment]
@18PatZ Testing now.

**Comment by FlyingPikachu** [comment]
That did the trick! Player data looks as it should. I see now that the completedQuests list [is already populated](https://github.com/18PatZ/Quests/blob/605b23defd92639bc11826e287eaec0d0dc6831b/src/main/java/me/blackvein/quests/Quester.java#L2713) before it reaches the block you've been working on, at which point the duplicate entry was added, so I guess @Blackvein goofed or redo-able quests weren't expected to be in the `completed-Quests` player /data list (perhaps they're only supposed to be in `completedRedoableQuests` - only he would know). At any rate, I'm satisfied :)

Thanks for your help! Meet you back on Spigotmc for your payment.

**Comment by SXRWahrheit** [comment]
Would it be possible to show completed repeatable quests as repeatable, and enable particle effects if they are available? As it stands, players are confused - the lack of particle effects over NPCs and the "completed" status in the available quests (not just their quest log) makes it appear as though the quest is not repeatable.

**Comment by FlyingPikachu** [comment]
@SXRWahrheit My mistake, I should've been more clear on Spigot. This is no longer the official repo. Please create a new issue at the link below:

https://github.com/FlyingPikachu/Quests/issues

But yes, it's possible :)

**Pull request merged**
