### PR TITLE
Module is closed too early

### PR DESCRIPTION
**Pull request by BerndiVader**

### CODE REVIEW

**Comment by FlyingPikachu** [comment]
@BerndiVader Hey Wahrheit, thanks for your PR.

A user had reported this issue to me via Spigot PM yesterday morning. I applied an identical fix for him to try and was surprised that it didn't work; it seems we cannot close the jar even at the end of the block or it breaks the API.

Reverting to not closing the module at all solves this issue. I had initially done it because Eclipse complained about it being a resource leak, but frankly I doubt it'll hurt anything.

Gonna close this and push what I have, but thank you again!

**Comment by FlyingPikachu** [comment]
Also, PRs should now be pushed to https://github.com/FlyingPikachu/Quests/pulls

**Comment by SXRWahrheit** [comment]
This is @BerndiVader's PR, not mine, just to be clear - he deserves all the credit!

**Comment by FlyingPikachu** [comment]
@SXRWahrheit My mistake, I misread your Spigot post lol

**Pull request closed without merging**
